apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: talks
  annotations:
    github.com/project-slug: arboleda-alejandro/talks
    backstage.io/techdocs-ref: dir:.
  description: Demo codes and slides from technology talks and presentations
spec:
  type: documentation
  lifecycle: experimental
  owner: user:default/arboleda-alejandro
  system: developer-hub

