apiVersion: v1
kind: Namespace
metadata:
  name: challenge-1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-1
  namespace: challenge-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-1
  template:
    metadata:
      labels:
        app: test-1
    spec:
      containers:
      - name: app
        image: busybox
        command: ["sh", "-c", "sleep 3600"]
        volumeMounts:
        - mountPath: /data
          name: data-volume
      volumes:
      - name: data-volume
        hostPath:
          path: /nonexistent-path
          type: Directory
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-2
  namespace: challenge-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-2
  template:
    metadata:
      labels:
        app: test-2
    spec:
      containers:
      - name: app
        image: busybox
        command: ["sh", "-c", "echo $MY_ENV && sleep 3600"]
        env:
        - name: MY_ENV
          valueFrom:
            configMapKeyRef:
              name: nonexistent-configmap
              key: key
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: limited-sa
  namespace: challenge-1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-3
  namespace: challenge-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-3
  template:
    metadata:
      labels:
        app: test-3
    spec:
      serviceAccountName: limited-sa
      containers:
      - name: app
        image: busybox
        command: ["sh", "-c", "kubectl get pods"]
---
