apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: challenge-4
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: arboledaalejandro/backend-demo:15.0.0  # Replace with your image
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            timeoutSeconds: 4        # TOO SHORT!
            periodSeconds: 5
            failureThreshold: 4      # TOO SENSITIVE!
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            timeoutSeconds: 10
            periodSeconds: 30
            failureThreshold: 3
            initialDelaySeconds: 30
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"
