apiVersion: v1
kind: Pod
metadata:
  namespace: challenge-3
  name: frontend-pod
  labels:
    app: frontend
spec:
  containers:
    - name: frontend
      image: curlimages/curl:latest
      command: ["/bin/sh"]
      args: ["-c", "while true; do sleep 30; done"]
      resources:
        requests:
          memory: "128Mi"
          cpu: "50m"
        limits:
          memory: "256Mi"
          cpu: "150m"

